#!/usr/bin/env bash
#
# mkwp 1.6.0 by Thomas Barregren <thomas@kntnt.com>
# =============================================================================


help() {

	echo -e "NAME
	mkwp - make wordpress

\e[1mSYNOPSIS\e[0m
	\e[1mmkwp\e[0m [OPTION]... NAME
	\e[1mmkwp\e[0m \e[1m--destroy\e[0m NAME

\e[1mDESCRIPTION\e[0m
	Makes a local WordPress site with the domain \e[1mname.ddev.site\e[0m where
	\e[1mname\e[0m is the domain name provided as the argument [NAME].

	If a flag is not specified on the command line, the corresponding
	option is in the first place set to a value read from the configuration
	file specified with \e[1m-c\e[0m or \e[1m--config\e[0m, in the second place to a value read
	from the configuration file \e[1m~/.mkwp\e[0m, and in the third place to a
	default value.

	If the configuration file \e[1m~/.mkwp\e[0m is missing, an empty one will be
	created.

	A configuration file should be formatted so that each line starting
	with the name of a long format flag, excluding leading double dashes
	(e.g. \e[1memail\e[0m instead of \e[1m--email\e[0m), followed by an equal sign, where the
	corresponding flag has not been specified on the command line, the flag
	is specified with the option set to the value following the equal sign.
	White space may be used around the equal sign.
	Examples:

		title = WordPress Test Site
		php=8.5

\e[1mOPTIONS\e[0m
	\e[1m-t <title>\e[0m
	\e[1m--title=<title>\e[0m
		The title of the WordPress site. If omitted, [NAME] will be
		used.

	\e[1m-d <path>\e[0m
	\e[1m--directory=<path>\e[0m
		The home directory of the website. If omitted, current
		directory will be used as home directory.

	\e[1m-n <dirname>\e[0m
	\e[1m--dirname=<dirname>\e[0m
		The name of the directory the site is created in, underneath the
		home directory. If omitted, [NAME] will be used.

	\e[1m-m <email>\e[0m
	\e[1m--email=<email>\e[0m
		The email address of the first user created in WordPress. If
		omitted, the current username is used as local-part and the
		hostname as domain.

	\e[1m-u <username>\e[0m
	\e[1m--user=<username>\e[0m
		The username of the first user created in WordPress. If
		omitted, the local-part of the email address will be used.

	\e[1m-p <password>\e[0m
	\e[1m--password=<password>\e[0m
		The password of the first user created in WordPress. Must at
		least be 12 characters long. If omitted, a 16 character random
		password is generated.

	\e[1m-l <locale>\e[0m
	\e[1m--language=<locale>\e[0m
		The language of the WordPress site. If omitted, en_US will be
		used. For a number of well-known locales, the site timezone is
		set accordingly (e.g. Europe/Stockholm for sv_SE).

	\e[1m-T <themes>\e[0m
	\e[1m--themes=<themes>\e[0m
		Comma separated list of themes to install. For a theme hosted
		on WordPress.org, enter its slug or URL to its zip-file. For a
		theme hosted in a remote Git repository, enter its remote URL.
		For a theme hosted locally, enter the path to the zip file. The
		last listed theme is activated. If omitted, WordPress's current
		default theme will be used.

	\e[1m-P <plugins>\e[0m
	\e[1m--plugins=<plugins>\e[0m
		Comma separated list of plugins to install. For a plugin hosted
		on WordPress.org, enter its slug or URL to its zip-file. For a
		plugin hosted in a remote Git repository, enter its remote URL.
		For a plugin hosted locally, enter the path to the zip file.

	\e[1m-M <plugins>\e[0m
	\e[1m--mu-plugins=<plugins>\e[0m
		Comma separated list of mu-plugins to install. For each plugin,
		provide the plugin's URL from where it can be downloaded as
		php-file (e.g. https://raw.githubusercontent.com/Kntnt/kntnt-
		adminbar-sanitizer/master/kntnt-adminbar-sanitizer.php).
		If omitted, no mu-plugins will be installed.

	\e[1m-V <version>\e[0m
	\e[1m--php=<version>\e[0m
		Version of PHP to be used. If omitted, PHP 8.5 will be used.

	\e[1m-W <version>\e[0m
	\e[1m--wp=<version>\e[0m
		Version of WordPress to install, given as <major>,
		<major>.<minor> or <major>.<minor>.<patch> (e.g. 6, 6.9 or
		6.9.4). Omitted parts are resolved to the highest available
		release. If omitted entirely, the latest version is installed.
		The core auto-update policy reflects the precision: a full
		<major>.<minor>.<patch> disables auto-updates, while <major> or
		<major>.<minor> enables patch-level updates only.

	\e[1m-R\e[0m
	\e[1m--redis\e[0m
		Adds a Redis service to the site and enables it as WordPress
		object cache backend: the Redis Object Cache plugin is
		installed and activated, and its object-cache.php drop-in is
		enabled. In a configuration file, use \e[1mredis = true\e[0m.

	\e[1m--destroy\e[0m
		Destroys the site [NAME]: deletes the DDEV project, including
		its database, and removes the site directory from the file
		system. Asks for confirmation before doing so. All other
		options are ignored.

	\e[1m-c <file>\e[0m
	\e[1m--config=<file>\e[0m
		Reads configuration from a file with the path <file>.
		See description above for details.

	\e[1m-h\e[0m
	\e[1m--help\e[0m
		Display this help and exit.

\e[1mDEPENDENCY\e[0m
	This command requires that a Docker provider is installed and running
	on your system and that DDEV is properly installed and in your path." | less -R

}

# Usage: die <message> <status>
# Echos the <message> and exit with the status code <status>
die() {
	echo -e "\033[0;31m${1:-}\033[0m" 1>&2
	exit "${2:-0}"
}

# Usage: extract_argument <variable> <args>...
# Validates that <args> starts with a short format flag followed by a value
# (e.g. -V 8.3) or a long format flag with an embedded value (e.g. --php=8.3),
# assigns the value to the global variable named <variable>, and sets the
# global variable shift_n to the number of arguments consumed (1 or 2).
extract_argument() {

	if [[ "$2" =~ ^--[^=]+=(.+)$ ]]; then # Long flag format, e.g. --php=8.3

		declare -g "$1"="${BASH_REMATCH[1]}"
		shift_n=1

	elif [[ "$2" =~ ^-[^-]$ && $# -ge 3 ]]; then # Short flag format, e.g. -V 8.3

		declare -g "$1"="$3"
		shift_n=2

	else

		die "Error: Missing option for $2" 12

	fi

}

# Usage: handle_arguments <args>...
# Parses <args>, which is expected to be the argument list from the command
# line, and creates corresponding variables containing options.
handle_arguments() {

	while [[ $# -gt 0 ]]; do
		case $1 in
			-h | --help) help; die ;;
			-t | --title=*) extract_argument title "$@"; shift $shift_n ;;
			-d | --directory=*) extract_argument directory "$@"; shift $shift_n ;;
			-n | --dirname=*) extract_argument dirname "$@"; shift $shift_n ;;
			-m | --email=*) extract_argument email "$@"; shift $shift_n ;;
			-u | --user=*) extract_argument user "$@"; shift $shift_n ;;
			-p | --password=*) extract_argument password "$@"; shift $shift_n ;;
			-l | --language=*) extract_argument language "$@"; shift $shift_n ;;
			-T | --themes=*) extract_argument themes "$@"; shift $shift_n ;;
			-P | --plugins=*) extract_argument plugins "$@"; shift $shift_n ;;
			-M | --mu-plugins=*) extract_argument mu_plugins "$@"; shift $shift_n ;;
			-V | --php=*) extract_argument php "$@"; shift $shift_n ;;
			-W | --wp=*) extract_argument wp "$@"; shift $shift_n ;;
			-R | --redis) redis=true; shift ;;
			--destroy) destroy=true; shift ;;
			-c | --config=*) extract_argument config "$@"; shift $shift_n ;;
			*) if [[ -z "$name" ]]; then name="$1"; shift; else die "Error: Invalid flag: $1" 2; fi ;;
		esac
	done

	[[ -n "$name" ]] || die "The required argument NAME is missing. See \033[1mmkwp -h\033[22m for more information." 5

}

# Usage: handle_config_files
# Reads options from the configuration file given with -c/--config, if any,
# and from ~/.mkwp, without overriding options already set on the command line.
handle_config_files() {

	# Create a list of files to read configuration from
	local files=()

	# Add config file to the list of configuration files if it exists and is readable
	if [[ $config ]]; then

		# Use /dev/stdin if config file is -
		if [[ "$config" == "-" ]]; then
			config="/dev/stdin"
		fi

		# Validate config file
		[[ -r $config ]] || die "Invalid path to config file" 10

		# Add the config file to the list of files to read configuration from
		files+=("$config")

	fi

	# Add ~/.mkwp file to the list of configuration files. Create ~/.mkwp if it doesn't exist.
	if [[ ! -e ~/.mkwp ]]; then
		touch ~/.mkwp || die "Couldn't create ~/.mkwp" 12
	fi
	[[ -r ~/.mkwp ]] || die "Couldn't read ~/.mkwp" 12
	files+=(~/.mkwp)

	# Read config files
	while IFS= read -r line || [[ "$line" ]]; do

		# Validate the line structure
		if [[ $line =~ ^(name|title|directory|dirname|email|user|password|language|themes|plugins|mu-plugins|php|wp|redis)[[:space:]]*=[[:space:]]*(.*) ]]; then

			# Extract keyword and value
			local key="${BASH_REMATCH[1]//-/_}"
			local value="${BASH_REMATCH[2]}"

			# If the global variable named in $key is empty, assign it the
			# value in $value. N.B. We know that $key contains a name of
			# an already declared global variable, since all variables names
			# in the regex above are declared before this function is called.
			if [[ -z ${!key} ]]; then
				eval "$key=$(printf "%q" "$value")"
			fi

		fi

	done < <(cat "${files[@]}")

}

# Usage: theme_to_activate <theme-list>
# Echo the slug of the last theme in the list of themes <theme-list>.
theme_to_activate() {

	(

		# Enable the extended pattern matching
		shopt -s extglob

		# Extract the last item of <theme-list>
		local theme=${1##*,}

		# Echo the basename without the suffix
		echo "${theme//+(*\/|.*)}"

	)

}

# Usage: make_unique_array <items>
# When called, <items> should be a comma-separated list of items. After the
# call, <items> contains an array where all items occur exactly once, in the
# order of their first occurrence.
make_unique_array() {

	# Uses name reference to refer to the original variable, which holds a
	# comma-separated string on entry and an array on return.
	local -n arr=$1

	# If the string is empty, set it to an empty array and return
	# shellcheck disable=SC2128
	if [[ -z "$arr" ]]; then
		arr=()
		return
	fi

	# Splits the string into an array at each comma
	local -a items
	# shellcheck disable=SC2128
	IFS=',' read -r -a items <<< "$arr"

	# Rebuild the array, keeping only the first occurrence of each item
	local -A seen=()
	local item
	arr=()
	for item in "${items[@]}"; do
		if [[ -z "${seen[$item]:-}" ]]; then
			seen[$item]=1
			arr+=("$item")
		fi
	done

}

# Usage: download_latest_tag <remote-git-repository-url>
# Clones <remote-git-repository-url> and checkout the latest tag.
# The local repository created in the process is removed. The argument
# <remote-git-repository-url> must be the URL to a remote repository.
# Example: https://github.com/Kntnt/kntnt-canvas.git
# Example: git@github.com:Kntnt/kntnt-canvas.git
download_latest_tag() {

	(

		# Enable Bash extended globbing features
		shopt -s extglob

		# Store the first argument of the function in 'repo', which should be the repository URL
		local repo=$1

		# Extract the repository name from the URL for use as the directory name
		local name=${repo//+(*\/|.*)}

		# The label of the tag or branch to be checked out
		local checkout=

		# Create a new directory named after the repository and change into it
		mkdir -p "$name"
		cd "$name"

		# Initialize a new Git repository and add a remote pointing to the original repository
		git init
		git remote add origin "$repo"

		# Fetch all tags from the remote repository, cleaning up any deleted references
		git fetch --prune --tags

		# Attempt to identify the latest tag in the remote repository
		local tag
		tag=$(git rev-list --tags --max-count=1)

		# If a tag is found, convert the tag hash to its name and checkout the tag
		if [[ -n $tag ]]; then

			# Convert the latest tag hash to the tag name
			checkout=$(git describe --tags "$tag")

			echo "Checking out tag: $checkout"

		# If no tags are found, try to find and checkout the default branch
		else

			# Fetch the name of the default branch from the remote repository, ensuring output in English
			local default_branch
			default_branch=$(LC_ALL=C git remote show origin | sed -n '/HEAD branch/s/.*: //p')

			# Fetch the latest state of the default branch and switch to it in a detached HEAD state
			git fetch origin "$default_branch"

			checkout="origin/$default_branch"

			echo "No tags found, attempting to check out the default branch: $default_branch"

		fi

		# Checkout the code
		git checkout "$checkout"

		# Remove the .git directory to clean up repository metadata from the local filesystem
		rm -rf .git

	)

}


# Usage: wp_install_zip <type> <path>
# Installs a local zip file with the path <path> as a theme or plugin, where
# <type> is `theme` or `plugin`. The file is temporarily copied into the
# project so that WP-CLI inside the container can reach it.
wp_install_zip() {

	local type="$1"
	local item="$2"

	# Temporarily copy the zip-file into the project and flush Mutagen so the
	# copy is visible inside the container.
	mkdir -p "$wp_path/.mkwp"
	cp "$item" "$wp_path/.mkwp/"
	item=".mkwp/$(basename "$item")"
	ddev mutagen sync

	# Install and remove the temporary copy.
	ddev wp "$type" install "$item"
	ddev exec rm -rf .mkwp

}

# Usage: install <list-name>
# Install the items listed in the array variable with the name <list-name> into
# a directory with the same name placed underneath the directory `wp-content`.
# For the intended function, <list-name> should be `themes`, `plugins` or
# `mu-plugins`.
install() {

	(

		local type=${1%s}
		# shellcheck disable=SC2178
		local -n items=${1//-/_} # Changes mu-plugins to mu_plugins
		local -a slugs=()

		cd "$wp_path/wp-content/$1"

		# Handle items that need special treatment one by one, and collect
		# plain slugs and zip URLs for a single batched WP-CLI install.
		for item in "${items[@]}"; do
			case "$item" in
				*.php) curl -OLf "$item" ;;
				*.git) download_latest_tag "$item" ;;
				*)     if [[ -f "$item" ]]; then wp_install_zip "$type" "$item"; else slugs+=("$item"); fi ;;
			esac
		done

		# Install all collected slugs and URLs in one WP-CLI call
		if (( ${#slugs[@]} )); then
			ddev wp "$type" install "${slugs[@]}"
		fi

	)

}

# Usage: resolve_wp_version <version>
# Resolves a possibly-partial WordPress version (e.g. 6, 6.9 or 6.9.4) to the
# highest released version that matches, by querying the WordPress.org API.
# Echoes the resolved version, or aborts if the fetch fails or nothing matches.
resolve_wp_version() {

	# Turn the requested version into a boundary-aware pattern so that, for
	# example, 6 matches 6.9.4 but not 16, and 6.9 matches 6.9.4 but not 6.90.
	local prefix="${1//./\\.}"

	# Fetch the list of released versions from wordpress.org
	local versions
	versions=$(curl -sf https://api.wordpress.org/core/stable-check/1.0/) || die "Couldn't fetch the list of WordPress versions from wordpress.org" 18

	# Keep the released versions matching the prefix and pick the highest one
	local resolved
	resolved=$(grep -oE '"[0-9]+\.[0-9]+(\.[0-9]+)?"' <<< "$versions" | tr -d '"' | grep -E "^${prefix}(\.|\$)" | sort -V | tail -1 || true)
	[[ "$resolved" ]] || die "No released WordPress version matches: $1" 19

	echo "$resolved"

}

# Usage: timezone_from_locale <locale>
# Echoes an IANA timezone matching the given WordPress locale, or nothing if
# the locale has no well-known timezone mapping.
timezone_from_locale() {

	case "$1" in
		sv_SE)         echo "Europe/Stockholm" ;;
		da_DK)         echo "Europe/Copenhagen" ;;
		nb_NO | nn_NO) echo "Europe/Oslo" ;;
		fi)            echo "Europe/Helsinki" ;;
		is_IS)         echo "Atlantic/Reykjavik" ;;
		en_GB)         echo "Europe/London" ;;
		ga)            echo "Europe/Dublin" ;;
		de_DE)         echo "Europe/Berlin" ;;
		de_AT)         echo "Europe/Vienna" ;;
		de_CH)         echo "Europe/Zurich" ;;
		fr_FR)         echo "Europe/Paris" ;;
		fr_BE | nl_BE) echo "Europe/Brussels" ;;
		nl_NL)         echo "Europe/Amsterdam" ;;
		es_ES)         echo "Europe/Madrid" ;;
		it_IT)         echo "Europe/Rome" ;;
		pt_PT)         echo "Europe/Lisbon" ;;
		pt_BR)         echo "America/Sao_Paulo" ;;
		pl_PL)         echo "Europe/Warsaw" ;;
		cs_CZ)         echo "Europe/Prague" ;;
		sk_SK)         echo "Europe/Bratislava" ;;
		hu_HU)         echo "Europe/Budapest" ;;
		et)            echo "Europe/Tallinn" ;;
		lv)            echo "Europe/Riga" ;;
		lt_LT)         echo "Europe/Vilnius" ;;
		el)            echo "Europe/Athens" ;;
		ro_RO)         echo "Europe/Bucharest" ;;
		bg_BG)         echo "Europe/Sofia" ;;
		uk)            echo "Europe/Kyiv" ;;
		tr_TR)         echo "Europe/Istanbul" ;;
		ja)            echo "Asia/Tokyo" ;;
		zh_CN)         echo "Asia/Shanghai" ;;
		*)             echo "" ;;
	esac

}

# Usage: destroy_site
# Deletes the DDEV project named $name, including its database, and removes
# the site directory from the file system. Asks for confirmation first.
destroy_site() {

	# Look up the project's root directory in DDEV's project registry. Keep
	# stdin away from ddev, which otherwise consumes the confirmation input
	# below when it is piped to the script.
	local json approot
	json=$(ddev describe "$name" -j 2> /dev/null < /dev/null) || die "No DDEV project named '$name' was found." 21
	[[ $json =~ \"approot\":\"([^\"]+)\" ]] || die "Couldn't determine the directory of the project '$name'." 22
	approot="${BASH_REMATCH[1]}"

	# Require the user to retype the project name before destroying anything
	echo -e "This will delete the DDEV project \e[1m$name\e[0m and remove the directory \e[1m$approot\e[0m."
	local confirmation
	read -r -p "Type the project name to confirm: " confirmation
	[[ "$confirmation" == "$name" ]] || die "Aborted." 23

	# Delete the DDEV project without keeping a snapshot, and remove the files
	ddev delete --omit-snapshot --yes "$name"
	rm -rf "$approot"

	echo "The site '$name' has been destroyed."
	exit 0

}

# =============================================================================


# If MKWP_DEBUG is defined, print a trace of simple commands, for commands,
# case commands, select commands, and arithmetic for commands and their
# arguments or associated word lists after they are expanded and before they
# are executed. The value of the PS4 variable is expanded and the resultant
# value is printed before the command and its expanded arguments.
[[ ${MKWP_DEBUG:-} ]] && set -x || MKWP_DEBUG=

# The return value of a pipeline is the value of the last (rightmost) command
# to exit with a non-zero status, or zero if all commands in the pipeline exit
# successfully.
set -o pipefail

# Treat unset variables and parameters other than the special parameters ‘@’ or
# ‘*’, or array variables subscripted with ‘@’ or ‘*’, as an error when
# performing parameter expansion. An error message will be written to the
# standard error, and a non-interactive shell will exit.
set -u

# Exit immediately if a command fails, also inside functions and subshells
# (-E makes the ERR trap inherited by them), and report what failed. Deliberate
# aborts go through die, which is not affected since it is always invoked
# behind || where errexit is suppressed.
set -eE
trap 'die "mkwp failed with exit code $? at line $LINENO: $BASH_COMMAND" $?' ERR

# The main script
(

	# Set options variables used by the script. Should another variable sneak into
	# the script, it's an error and `set -u` aborts the execution.
	name=
	title=
	directory=
	dirname=
	email=
	user=
	password=
	language=
	themes=
	plugins=
	mu_plugins=
	php=
	wp=
	redis=
	destroy=
	config=
	shift_n=

	# Parse the argument list from the command line
	handle_arguments "$@"

	# Normalize the site name, which doubles as DDEV project name and domain
	name=${name,,}

	# In destroy mode, tear down the site and exit; nothing below applies
	if [[ $destroy ]]; then
		destroy_site
	fi

	# Parse config files
	handle_config_files

	# Tidy up, fill in default values and add some extra variables.
	title=${title:=${name^}}
	directory=${directory:=$(pwd)}
	dirname=${dirname:=$name}
	email=${email:=$(whoami)@$(hostname)}
	user=${user:=${email%@*}}
	password=${password:=$(LC_ALL=C tr -dc 'a-zA-Z0-9!#$%&()*+,-./:;<=>?@[\]_{|}' < /dev/urandom | head -c 16 || true)}
	language=${language:=en_US}
	themes=${themes:=}
	php=${php:=8.5}
	wp_path="$directory/$dirname"
	url="https://$name.ddev.site"

	# Normalize the redis option, which may come from a config file as text
	case "${redis,,}" in
		'' | false | no | 0) redis= ;;
		true | yes | 1)      redis=true ;;
		*)                   die "Invalid value for redis: $redis" 24 ;;
	esac

	# Echo all parameters used by the script if debugging.
	if [[ $MKWP_DEBUG ]]; then
		echo "name=$name"
		echo "title=$title"
		echo "directory=$directory"
		echo "dirname=$dirname"
		echo "email=$email"
		echo "user=$user"
		echo "password=$password"
		echo "language=$language"
		echo "themes=$themes"
		echo "plugins=$plugins"
		echo "mu_plugins=$mu_plugins"
		echo "php=$php"
		echo "wp=$wp"
		echo "redis=$redis"
		echo "config=$config"
		echo "wp_path=$wp_path"
		echo "url=$url"
	fi

	# Check that DDEV is working
	ddev debug dockercheck &> /dev/null || die "Error: Check that a Docker provider is installed and running and that DDEV is properly installed" 1

	# Validate options
	ddev_projects=$(ddev list -j)
	if echo "$ddev_projects" | grep -q "\"approot\":\"$wp_path\""; then die "A DDEV project already exists in the directory $wp_path." 15; fi
	if echo "$ddev_projects" | grep -q "\"name\":\"$name\""; then die "A project named '$name' already exists in DDEV." 16; fi
	[[ "$name" ]] || die "Error: Missing name of the project." 3
	[[ "$name" =~ ^[[:alpha:]]([[:alnum:]-]*[[:alnum:]])?$ ]] || die "Invalid name: $name. A DDEV project name must start with a letter and may otherwise only contain letters, digits and hyphens. Use -n/--dirname to name the site directory freely." 11
	[[ "$dirname" =~ ^[^/]+$ && "$dirname" != "." && "$dirname" != ".." ]] || die "Invalid dirname: $dirname" 20
	[[ "$title" =~ ^[[:print:]]+$ ]] || die "Invalid title: $title" 4
	[[ "$email" =~ ^[[:alnum:]._%+-]+@[[:alnum:].-]+\.[[:alpha:]]{2,}$ ]] || die "Invalid email address: $email" 6
	[[ $password =~ ^[[:print:]]{12,}$ ]] || die "Invalid password. Must be at least 12 characters." 7
	[[ "$language" =~ ^[[:lower:]]{2}(_[[:upper:]]{2})?$ ]] || die "Invalid language code: $language" 8
	[[ "$php" =~ ^7\.[0-4]$|^8\.[0-5]$ ]] || die "Invalid PHP version: $php" 9
	[[ -z "$wp" || "$wp" =~ ^[0-9]+(\.[0-9]+){0,2}$ ]] || die "Invalid WordPress version: $wp" 17
	[[ ! -e "$wp_path" ]] || die "$wp_path already exists" 13
	[[ -d "$directory" && -w "$directory" ]] || die "Cannot create $wp_path" 14

	# Create and enter the WordPress root directory.
	mkdir -p "$wp_path"
	cd "$wp_path"

	# Configure the project before the first start, so that all customizations
	# below — PHP settings, host commands, cron and the optional Redis service
	# — are baked into the containers in a single start with no restart needed.
	ddev config --project-type=wordpress --disable-settings-management --php-version="$php" --performance-mode=mutagen

	# Create local php.ini with infinite timeout. Don't use on production!
	mkdir -p .ddev/php
	cat <<- 'EOT' > .ddev/php/my-php.ini
	[PHP]
	; Don't do this in production :-p
	max_input_time = 0          ; infinite time
	max_execution_time = 0      ; infinite time
	default_socket_timeout = -1 ; infinite time
	EOT

	# Create host commands 'enter'
	mkdir -p .ddev/commands/host
	cat <<- 'EOT' > .ddev/commands/host/enter
	#!/usr/bin/env bash
	ddev ssh --dir="$(ddev exec pwd)/$(realpath --relative-to=$DDEV_APPROOT $(pwd))" "$@"
	EOT

	# Create host commands 'here'
	cat <<- 'EOT' > .ddev/commands/host/here
	#!/usr/bin/env bash
	ddev exec --dir="$(ddev exec pwd)/$(realpath --relative-to=$DDEV_APPROOT $(pwd))" "$@"
	EOT
	chmod +x .ddev/commands/host/enter .ddev/commands/host/here

	# Install the cron add-on and schedule WordPress cron to run every minute
	ddev add-on get ddev/ddev-cron
	cat <<- 'EOT' > .ddev/web-build/wp.cron
	* * * * * IS_DDEV_PROJECT=true /usr/local/bin/wp --path=/var/www/html cron event run --due-now > /dev/null 2>&1
	EOT

	# Add a Redis service to be used as WordPress object cache backend
	if [[ $redis ]]; then
		ddev add-on get ddev/ddev-redis
	fi

	# Start the Docker containers
	ddev start

	# Download WordPress without the default themes and plugins, which saves
	# both download and file synchronization time; themes to use are installed
	# further down. When a version is requested, derive the core auto-update
	# policy from how precisely it was given, resolve any omitted parts to the
	# highest available release, and download that exact version.
	if [[ "$wp" ]]; then
		case "$wp" in
			*.*.*) wp_auto_update=false ;;      # exact x.y.z: pin, no auto-updates
			*)     wp_auto_update="'minor'" ;;  # x or x.y: only patch (.z) auto-updates
		esac
		wp=$(resolve_wp_version "$wp") || exit $?
		echo "Installing WordPress $wp"
		ddev wp core download --version="$wp" --locale="$language" --skip-content
	else
		wp_auto_update="'minor'"
		ddev wp core download --locale="$language" --skip-content
	fi

	# Flush Mutagen so the downloaded files are visible on the host
	ddev mutagen sync

	# Create wp-config.php
	ddev wp config create --dbname=db --dbuser=db --dbpass=db --dbhost="ddev-$name-db" --dbprefix=wp_ --dbcharset=utf8mb4 --dbcollate=utf8mb4_unicode_ci --locale="$language" --extra-php <<- EOT
	define( 'WP_ENVIRONMENT_TYPE', 'local' );
	define( 'DISABLE_WP_CRON', true );
	define( 'WP_MEMORY_LIMIT', '128M' );
	define( 'WP_MAX_MEMORY_LIMIT', '256M' );
	define( 'DISALLOW_FILE_EDIT', true );
	define( 'WP_AUTO_UPDATE_CORE', ${wp_auto_update} );
	define( 'MEDIA_TRASH', true );
	define( 'EMPTY_TRASH_DAYS', 90 );
	define( 'WP_DEBUG', true );
	define( 'WP_DEBUG_LOG', true );
	define( 'WP_DEBUG_DISPLAY', false );
	EOT

	# Install WordPress
	ddev wp core install --url="$url" --title="$title" --admin_user="$user" --admin_password="$password" --admin_email="$email" --skip-email

	# Use pretty permalinks instead of the default plain ones
	ddev wp rewrite structure '/%postname%/'

	# Set the site timezone when one can be derived from the language
	timezone=$(timezone_from_locale "$language")
	if [[ $timezone ]]; then
		ddev wp option update timezone_string "$timezone"
	fi

	# If no theme is specified, default to WordPress's current default theme,
	# whose slug is declared among core's default constants.
	if [[ -z "$themes" ]]; then
		themes=$(sed -n "s/.*'WP_DEFAULT_THEME', '\([^']*\)'.*/\1/p" wp-includes/default-constants.php)
		[[ "$themes" ]] || die "Couldn't determine the default theme." 25
	fi

	# Get the theme to activate
	theme=$(theme_to_activate "$themes")

	# Remove duplicates from list of themes and plugins and convert them to
	# arrays, keeping the original order.
	make_unique_array themes
	make_unique_array plugins
	make_unique_array mu_plugins

	# Create home for "must use" plugins
	mkdir -p wp-content/mu-plugins/DISABLED
	cp wp-content/index.php wp-content/mu-plugins

	# Install themes and plugins
	install themes
	install plugins
	install mu-plugins

	# Activate the last listed theme
	ddev wp theme activate "$theme"

	# Enable Redis as object cache backend: install and activate the Redis
	# Object Cache plugin, point it to DDEV's Redis service, and enable the
	# object-cache.php drop-in.
	if [[ $redis ]]; then
		ddev wp plugin install redis-cache --activate
		ddev wp config set WP_REDIS_HOST redis
		ddev wp redis enable
	fi

	# Launch site
	ddev launch

	# Inform user.
	echo -e "\e[1;30;103m\n\nYou should now see your new WordPress site in your browser.\n\nUsername: $user\npassword: $password\n\e[0m"

# Propagate the subshell's exit status without triggering the ERR trap again
# at the top level, which would repeat the already reported error.
) || exit $?
